global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'alertmanager'
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'go-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['go-webserver:8080']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
